name: Node.js CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Setup node
        run: npm install
        
      - name: test node
        run: npm test



# name: ci-node-workflow
# #on: [push]
# on:
#   pull_request:
#     branches:
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node: [ 14 ]
#     name: Node ${{ matrix.node }} sample
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node }}
#       - run: npm ci
#       - run: npm test
      

