name: Node.js CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Setup node
        run: npm install
        
      - name: test node
        run: npm test

